dist: trusty
language: java
env:
  global:
  - DISPLAY=:99.0
  - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2048m -Xms1024m"
  matrix:
  - PROFILE=platform-oxygen,tests
  - PROFILE=platform-photon,tests,updatesites
  - PROFILE=platform-sirius-5.1,tests
  - PROFILE=platform-sirius-6.0,tests
  - PROFILE=platform-sirius-6.1.0,tests
  - PROFILE=platform-sirius-6.1.1,tests
  - PROFILE=platform-sirius-6.1.2,tests
  - PROFILE=platform-sirius-6.1.3,tests
jdk:
- oraclejdk8
sudo: required
install: true
before_script:
# for RCPTT tests
- export SWT_GTK3=0
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1440x900x16"
- sh -e /etc/init.d/xvfb start
# for the web site
- sudo add-apt-repository ppa:brightbox/ruby-ng -y
- sudo apt-get update
- sudo apt-get install ruby-dev ruby-full
- gem install addressable --version '= 2.4.0'
- gem install jekyll
- gem install jekyll-paginate
- gem install jekyll-gist
- gem install pygments.rb
- gem install redcarpet
- gem install RedCloth
script:
# Build documentation web site
- mkdir web-site
- cd web-site
- echo "Clone gh-pages"
- git clone https://$GH_TOKEN@github.com/ObeoNetwork/M2Doc.git -b gh-pages --quiet .
- if [[ "$TRAVIS_TAG" != "" ]]; then chmod a+x ./promote.sh; ./promote.sh ${TRAVIS_TAG}; fi
- echo "Build gh-pages"
- jekyll build
- ls
# copy to documentation plugin
- echo "Copy to documentation plugin"
- mkdir ../plugins/org.obeonetwork.m2doc.doc/doc
- cp -Rf _site/* ../plugins/org.obeonetwork.m2doc.doc/doc/
- cd -
# Java build
- mvn -v
- mvn clean verify -fae -P$PROFILE
- export TAG_OR_BRANCH="${TRAVIS_BRANCH}/nightly"
- if [[ "$TRAVIS_TAG" != "" ]]; then export TAG_OR_BRANCH="${TRAVIS_TAG}"; fi
- if [[ "$PROFILE" == *"updatesites"* ]]; then chmod a+x prepare-deploy-local-dir.sh && ./prepare-deploy-local-dir.sh
  $TRAVIS_BUILD_DIR/$TAG_OR_BRANCH; export UPDATE_SITES=true; fi
after_script:
- if [[ "$TAG_OR_BRANCH" != "" ]]; then chmod a+x travis-promote.sh && ./travis-promote.sh;
  fi
deploy:
- provider: s3
  access_key_id: AKIAI7GYGSUKTIBLAI6Q
  secret_access_key:
    secure: A2AARWNQrm5bddsfzArzH8miOVvoTjT/Y1P6CMUHqiwKRE46mYEPqVxy+CIPtVa8SmvFTL/IRxb8zQ8FPBSTasB0vzz94yxtVJvwn+kkPM+z0YdzOfonJo4BjKO+NHzgncOpvBngMqboU5RzS+pqQ6xUhALhHEATCARsYF0NUgsEjGZ8JJJSzAbfQ7oaL6xbuon/72ABJOIQbg9sesq7YFl+/9bHcOl1SU5owF9hIa/b6IB3iEmg1L2vzYP2L/x+BGPwpMkDfRGMUBJByf3e8q6mvPYU/5XVQrqo2WnD9JGQB62OOi/DlRQ0cHxXP9x5iRd1hVqMJZMduAAa5ymK8UOV5h1+xkBFJMQZ3UQbZ3FEG/0rYFEVZ/ynj8H05/nO1DxqTiGSaCIlbF8hEWvcqfoK/cT+v+9i4GJ3jael03Um90U7L2fI098VYJmAuWqcYyNTqDVb5hwD77ULvT2b13vtVAGEJO1h3UoAy4xOMuOCCw3JezAA0UOL3mw2+F9syZ68Sm5yUXRZHuajSzAdpeD3X7tOO4cC6YCvUVkBXRLWozWmI64/6WL/FhNdux/GMlRqWGbxQPg43pZfGs6VQD/p1BGpZTFk9zuQix0UMLPxfvjwkLYt97KK6KmbCv1YE8IedhkdBeVDh9OETPFa5/N9lGxocpraVivYYzmyHDg=
  bucket: obeo-m2doc-releases
  local-dir: "${TRAVIS_BUILD_DIR}/${TAG_OR_BRANCH}"
  acl: public_read
  skip_cleanup: true
  region: eu-west-1
  upload-dir: ${TAG_OR_BRANCH}
  on:
    all_branches: true
    repo: ObeoNetwork/M2Doc
    condition: $UPDATE_SITES = true

